use std::env;
use std::path::PathBuf;
use std::process::{Command, Stdio};

use serde_json::{Value, json};

pub(super) fn workspace_dependency_report(cwd: &PathBuf) -> Value {
    let python = resolve_executable("python3").or_else(|| resolve_executable("python"));
    let python_modules = python
        .as_ref()
        .map(|python_bin| {
            json!({
                "docx": python_module_available(python_bin, "docx"),
                "openpyxl": python_module_available(python_bin, "openpyxl"),
                "pdfplumber": python_module_available(python_bin, "pdfplumber"),
                "pypdf": python_module_available(python_bin, "pypdf"),
                "pptx": python_module_available(python_bin, "pptx"),
            })
        })
        .unwrap_or(Value::Null);

    json!({
        "runtime": "codex-gateway",
        "cwd": cwd.display().to_string(),
        "os": env::consts::OS,
        "arch": env::consts::ARCH,
        "executables": {
            "node": resolve_executable("node"),
            "npm": resolve_executable("npm"),
            "python": python,
            "cargo": resolve_executable("cargo"),
        },
        "pythonModules": python_modules,
        "note": "This report is generated by the gateway host runtime, not by the Codex desktop app thread dependency bundle."
    })
}

fn resolve_executable(name: &str) -> Option<String> {
    let paths = env::var_os("PATH")?;
    env::split_paths(&paths)
        .map(|path| path.join(name))
        .find(|candidate| candidate.is_file())
        .map(|candidate| candidate.display().to_string())
}

fn python_module_available(python_bin: &str, module: &str) -> bool {
    Command::new(python_bin)
        .arg("-c")
        .arg(format!("import {module}"))
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .map(|status| status.success())
        .unwrap_or(false)
}
